# We need sudo, in order to install and run Docker.
sudo: required
services:
  - docker

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

matrix:
  allow_failures:
    - python: "nightly"

before_script:
  - docker version
  - ./test_setup.sh

script:
  - ./run_nosetests.sh
  - sudo pip install .
  - ./run_full_tests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
