# We need sudo, in order to install and run Docker.
sudo: required
services:
  - docker

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

matrix:
  allow_failures:
    - python: "nightly"

before_script:
  - ci/install_musl-libc.sh
  - docker version
  - ./test_setup.sh

script:
  - CC=/usr/local/musl/bin/musl-gcc make
  - ./run_nosetests.sh
  - sudo pip install .
  - ./run_full_tests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: jreinhart
  password:
    secure: kbjV+UQNXYZbW3jGMaEvK4wYUorVMyrzn5fdVqKmTMLVB6Rl/MwABi5O8ciVHf0bAZzi1xuGud399zLEMWG0P5fYE5UfJplRTg22p/urwZ7OoLQGgD8v5QcOfyyPOGxriapE0I05VdrVi1MUeD6mwQLVOnrVPOSBW/PWvgguyyW9tqWkHCo7flhx8Me5EgD3+39d9027Uaw8IGZFvwCiB6xghOJn8vr2ADhGA/yZtx674UOkmiVMrh7eFLnbSHxiWemTCsf1UiqKF7UyQ7Z6j5qTno+HWPX++Z8nsAdma48jYJQt6OIfXgz8TIStuJxzile5l67TqEZ8QNN7bjggkUKSMSS+v91E0fkc35saGZqKIXQ1Mj3xDgCk91kyaahNfo+pnrxb/wyc/3PaXkTnm517v/b8J6tUR583pYnNcfhiPQWnNGCYI3T0I2JSAvVaCMc3ab0B9jSxia5maiL9AtuPNHa1aB97hgTxQHYazCd8a7X0Bnvl/eiFsr9XQudDM8AG2U8wvKmbf/MCZlMMvptD7UNP1KXEhoUih4XtOKnYeCrpgW9ID83RSae6ClqtQBxTZlRoh9nzxBQMa6NbM3+I6cpDUgfP3oMzMrqaJ38eVlgT7ReFUcfNVb7MworCkca1lNKPLNo1zib0+sWwqbqLSTwP/7+gW5EGkO1fPzU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: JonathonReinhart/scuba
