name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
    - name: Unshallow checkout
      run: git fetch --prune --unshallow

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Build
      env:
        CC: /usr/bin/musl-gcc
      run: python -m build

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
